### ISSUE TITLE
how to run a nmt example

### ISSUE THREAD

**Issue by vinayakumarr** [rsennrich/nematus#11]
Could you please provide steps for cpu

**Comment by rsennrich** [comment]
check the test directory for commands to translate with an existing model, or train a simple toy model. To train a full-scale system, check the scripts and instructions at https://github.com/rsennrich/wmt16-scripts/tree/master/sample

Beware that training on CPU is about 50-80 times slower than on a recent GPU, so training a model would take a year rather than a week.

**Comment by vinayakumarr** [comment]
I want know which deep learning algorithms you used do you have any paper. I have my own data set .  Is it possible to run for my data set

**Comment by rsennrich** [comment]
please see the end of the README file for a list of references that describe the implemented algorithms. The code mostly follows the paper by Bahdanau et al. (2015), but deviates in some places, as described here:

https://github.com/nyu-dl/dl4mt-tutorial/blob/master/docs/cgru.pdf
https://github.com/emjotde/amunmt/blob/master/notebooks/dl4mt.ipynb

On a slightly different topic, I've now created a google group ( nematus-support@googlegroups.com ) as the most appropriate place for general support requests: https://groups.google.com/d/forum/nematus-support , so that the Github issues page can be reserved for development.

best wishes,
Rico
