### ISSUE TITLE
Training speed benchmarks

### ISSUE THREAD

**Issue by mkaeshammer** [rsennrich/nematus#42]
Hi,

We are looking into training speed, using the test_train.sh script. Comparing our numbers to the benchmarks currently reported in the [readme](https://github.com/rsennrich/nematus/blob/master/README.md), our "words/s" numbers are in the range of the reported "sentences/s". So either our training is really slow, or the benchmark numbers should actually be words per second.

Comparing [a commit from November](https://github.com/rsennrich/nematus/blob/deac2aaf0ade1676e683624900c7cc1b988640a4/nematus/nmt.py#L928) (when the benchmarks where added) to the current version, supports the latter hypothesis. Could you confirm and adapt the benchmark numbers?

Thank you!

**Comment by rsennrich** [comment]
Hi Miriam,

the numbers reported in the README are sentences/s. You can find more numbers (including words/s) on slides 76-77 here: http://www.statmt.org/eacl2017/practical-nmt.pdf

**Comment by aeloyq** [comment]
Hi @rsennrich 

excuse me, i running the nmt.py on a pc with(i7 4790 gtx1080ti theano 0.10.0dev1 cuda8 cudnn5.1) but got a speed at 101sentences/s and nearly 5G~6G memory usage with new theano backend (22 words per sentence on average). Is that unnormal?

will any ops like T.sum be run on cpu instead of gpu which may slow down the speed(i7 4790 seems slower than E5)

**Comment by rsennrich** [comment]
Hello,

this is hard to answer because training speed depends on your 
hyperparameters. You can run the script 'test/test_translate.sh', for 
which benchmark results on different hardware is in the README and here: 
http://www.statmt.org/eacl2017/practical-nmt.pdf#page=115

The memory consumption is high. There might be a problem in the theano 
0.10 branch; you should also consider this issue in theano 0.9: 
https://github.com/Theano/Theano/issues/5382
We generally use libgpuarray.preallocate=0.8 (or some other value) to 
avoid this problem.

best wishes,
Rico

**Comment by aeloyq** [comment]
Thanks for your reply!
Actually a used high-lighted hyperparameters shown below(other hyperparameters was used by using defualt value).(0.10.0 performs 0.9.0 i tried both)

![image](https://user-images.githubusercontent.com/20637250/27233941-e183dc30-52ed-11e7-91de-9b8f1b1dc3d5.png)

it seems that we have a little bit diference:
1080ti                            /                     1080
5.5GB-101sent/s           /           4.9GB-110sent/s

May these problem cause slowing down:

1. I/O from cpu to gpu

2. indexing or sum ops on cpu

3.temperature(68C)

**Comment by rsennrich** [comment]
oh, then you're close to the results we report - this can easily be due 
to random variation, or having slightly longer sentences (on average) in 
your dataset.

**Comment by aeloyq** [comment]
ok, I see!

By the way, How can I know how much memory i used if i use

libgpuarray.preallocate=0.8`

**Comment by aeloyq** [comment]
Thank you !

**Comment by rsennrich** [comment]
gpuarray.preallocate=X with X<1 is interpreted as a percentage of available memory; X>1 is interpreted as an absolute number (in MB). See here: http://deeplearning.net/software/theano/library/config.html

**Comment by aeloyq** [comment]
ok... 
I meant how much memory will the program truly use...
err...
For example:
If I preallocated 80% memory, I will find that the memory usage displayed by nvidia-smi is fixed to 80% of total memory while the program may just use 50% of them. 
I'm concern about the real usage(which is 50% in the example)...

**Comment by rsennrich** [comment]
Follow the instructions on this page to profile peak memory usage in 
Theano: http://deeplearning.net/software/theano/tutorial/profiling.html

The relevant function call is currently in the last line in nmt.py , and 
needs to be uncommented.

best wishes,
Rico

**Comment by aeloyq** [comment]
Wow！
I almost forget it!
Thank you very much!
