### ISSUE TITLE
n_factors related bug in nmt.py

### ISSUE THREAD

**Issue by cshanbo** [rsennrich/nematus#45]
Hi all,

There are 2 potential conditions that might encounter a `list index out of range` exception (see below) in `nmt.py` [here](https://github.com/rsennrich/nematus/blob/master/nematus/nmt.py#L68) (condition 1) and `data_iterator.py` [here](https://github.com/rsennrich/nematus/blob/master/nematus/data_iterator.py#L137) (condition 2)

1. When the first sentence of a mini-batch is an empty line and the [skip_empty](https://github.com/rsennrich/nematus/blob/master/nematus/data_iterator.py#L21) flag is not set as `True`.
2. When we don't want to use any factor other than the word itself, but the first sentence of a mini-batch startswith a `|` symbol in the training data. 
I think it's better that we use a `try, exception` to capture such exceptions.
I'll test it and raise a PR if you want.

##############################
The exception is like:
```
Traceback (most recent call last):
  File "../../nematus/nmt_worker.py", line 666, in <module>
    update_algorithm=args.update_algorithm
  File "../../nematus/nmt_worker.py", line 443, in train_on_multi_gpu
    epoch, x, x_mask, y, y_mask = get_one_mini_batch(train_it)
  File "../../nematus/nmt_worker.py", line 422, in get_one_mini_batch
    n_words=n_words)
  File "/nematus/nmt.py", line 68, in prepare_data
    n_factors = len(seqs_x[0][0])
IndexError: list index out of range

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by rsennrich** [comment]
Hi Justin,

thanks for reporting these problems. I think they'll need two different 
code changes to address them:

1. your fix doesn't cover the case where you have more than 2 factors, 
but the first sentence is empty. I suggest to pass the number of factors 
as an argument to prepare_data (it is stored in the model_options 
dictionary), rather than getting it from the text.

2. "|" is currently reserved as a factor-separator, even if num_factors 
is 1, and segmentation into factors is performed in line 137 in 
data_iterator.py. To fix this exception, TextIterator should be provided 
with a boolean saying whether the text is factored, and the 
factor-splitting code should only be conditionally executed if the 
boolean is True.

could you write a PR with those changes?

best wishes,
Rico
